### ISSUE TITLE
Live test does not work on IE11

### ISSUE THREAD

**Issue by youngrrrr** [WebReflection/import.js#1]
The live test at https://webreflection.github.io/import.js/ does not work in IE11. Is it supposed to?

The console produces the error message: 'Promise' is undefined import.js (58,7)

**Comment by WebReflection** [comment]
I guess that's because no polyfill is provided. Have you tried providing one?

**Comment by petrosmm** [comment]
@youngrrrr try adding `<script crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js?features=Promise%2CPromise.prototype.finally"></script>`

**Comment by petrosmm** [comment]
@youngrrrr so I actually was able to get it working on IE11,
1. in `index.html` add `<script crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js?features=Promise%2CPromise.prototype.finally%2Cfetch"></script>` at the top near the comment. this polyfill service will provide you with `Promise()`
2. inside `js/main.js` you will find an arrow function, (as you gain experience you remember that arrow functions are not supported in earlier browsers)... unfortunately IE11 is so old and not intuitive so it did not tell i found by tinkering... 
```
import(fileName).then(module => {
    module.default();
});
```
needs to be replaced with
```
import(fileName).then(function (module) {
  module.default();
});
```

and it will light up green, kudos to @WebReflection for researching and creating a solution for this entire project in the first place!

**Comment by WebReflection** [comment]
Thanks @petrosmm for providing a work around, as the example wasn't meant to run out of the box in IE11, but the library does.

Closing, as I don't really care much about IE11, but this issue would be helpful for others in the future.
