### ISSUE TITLE
Feature request: Ponyfill

### ISSUE THREAD

**Issue by jonaskello** [WebReflection/import.js#2]
I would like to have a [ponyfill](https://github.com/sindresorhus/ponyfill) version of this so I can do:

```
import { import } from "import-ponyfill";

import("./foo/bar").then((m) => m.foo());
```

If `import()` has native support like in Chrome 63 then this ponyfill does nothing but proxy to that function. Otherwise it uses the code in this repo.

I think this would be similar to how the [fetch-ponyfill](https://github.com/qubyte/fetch-ponyfill) works but for modules.

Would it be possible to do something like this?

**Comment by WebReflection** [comment]
> If import() has native support like in Chrome 63 then this ponyfill does nothing but proxy to that function.

it won't work like that, `import` is static, not a real function.

**Comment by jonaskello** [comment]
So this polyfill does not proxy to native import() ?

In that case, the ponyfill could just do the same, i.e. not proxy at all. It would then use the emulated code in all browsers but if this is how the polyfill works nothing would be lost?

**Comment by jonaskello** [comment]
Or perhaps your concern is it about the name clash? In that case the ponyfill could just export `_import` similar to how [this polyfill](https://github.com/yukulele/dynamic-import-polyfill) works.

**Comment by WebReflection** [comment]
> So this polyfill does not proxy to native import() ?

that is not possible. `import` is static. You can't have `import` as function. This works in a way that is transparent for your code and the day your targets will be natively compatible with dynamic `import(...)` you'll just remove the entry point of this file.

Nothing will change, nothing will be named `_import` or the whole point will be missed.

**Comment by jonaskello** [comment]
> import is static. You can't have import as function. 

Yes, I do understand that import is static and not a real function etc. I have read the spec several times. However I don't see how that is relevant for a ponyfill.

> Nothing will change, nothing will be named _import or the whole point will be missed.

Agreed, this is the whole point of a *polyfill*. However my request was about a  *[ponyfill](https://github.com/sindresorhus/ponyfill)*. If you are not familiar with this concept, a short explanation would be that you import the functionality that is traditionally polyfilled as a regular import instead of having something polyfill it at a static level like adding it to window. Please see the link, which does a better job of explaining it than I can.

Sidebar: My main issue with the way this polyfill works right now is that it requires you to define a special entrypoint. The native import() is specified to work both for [scripts and module](https://developers.google.com/web/updates/2017/11/dynamic-import). So to successfully polyfill it you would have to make it available to scripts so you can do this (example copied from the previously referenced link):

```
<script>
  const main = document.querySelector('main');
  const links = document.querySelectorAll('nav > a');
  for (const link of links) {
    link.addEventListener('click', async (event) => {
      event.preventDefault();
      try {
        const module = await import(`/${link.dataset.entryModule}.mjs`);
        // The module exports a function named `loadPageInto`.
        module.loadPageInto(main);
      } catch (error) {
        main.textContent = error.message;
      }
    });
  }
</script>
```

**Comment by WebReflection** [comment]
> If you are not familiar with this concept ...

I've written dozen polyfills and pony fills in my life, no need to explain.

What I need to re-state, is that it's not going to work. You cannot `import { import } from "import-ponyfill";`, do you understand?

If you have any other name in the process you can just get rid of this library all together and use any loader.

> it requires you to define a special entrypoint

exactly, and that's the only way it can work because it needs to resolve relative paths while loading modules.

As summary: I'm sorry this is not the library, neither the solution, you are looking for.

You can fork it and try to see if you find a way to do what you want. I hope for you it'll work.

**Comment by jonaskello** [comment]
Yes, I do understand the name clash (and `import` is even a keyword in es6). What I'm saying is that if you just use a different name, then a ponyfill would be fine, and IMO a ponyfill does not need to have the exact name of the native functionality, but a polyfill need to. I think the confusion is just that we see this differently. And I understand your point, it feels more like you are using the standard if the name matches.

You're right, I could use any loader, and I am currently using SystemJS. However I was looking for something more standard compliant and more lightweight. Like a loader that mimics the behaviour of dynamic import(). SystemJS really is overkill for my simple use-case (loading an ES module dynamically). I've spent most of today searching for something like that but have not found anything. If you know of such a loader I would very much appreciate a link 👍 .

Sure, if I find the time I'll fork this and make it into a a loader that mimics import() (which to me is the same thing as a ponyfill for import()).

**Comment by WebReflection** [comment]
https://www.youtube.com/watch?v=BoLd3cMc0jQ
