### ISSUE TITLE
Add  ` xhr.overrideMimeType("text/plain");` to resolve XML Parsing Error(s) in Firefox

### ISSUE THREAD

**Issue by ken-okabe** [WebReflection/import.js#3]
Thanks for the great library.

To test locally, I found errors in firefox: XML Parsing Error(s)

to resolve the error:

add 1 line:

`xhr.overrideMimeType("text/plain");`

to 

https://github.com/WebReflection/import.js/blob/master/import.js

          var xhr = new XMLHttpRequest();
          xhr.overrideMimeType("text/plain");
          xhr.open('GET', path);
          xhr.onerror = reject;
          xhr.onload = function () {//.............

**Comment by WebReflection** [comment]
you have an issue and a solution, all you need to contribute now is a PR

**Comment by ken-okabe** [comment]
I think you are the maintainer, so can you.
