### ISSUE TITLE
Use from within web workers 

### ISSUE THREAD

**Issue by jimmywarting** [WebReflection/import.js#5]
Web workers don't have XHR or DOM

1. Would it be possible to replace XHR with fetch instead?
2. Could you change createElement('script') with either eval or constructing a new Function?

My end goal would be to have it in service worker and use async import
doe it's somewhat restricted and i guess it wasn't meant to support async import at first, I mean `importScript` stops working after it have been installed.
it's only possible to use it durning the installation face, so i would have to use either eval or a Function constructor if i want to add dynamic code.

**Comment by WebReflection** [comment]
This module hasn't been touched for the last 4 years, and the fact Web Workers don't support ESM import is a *shame* of the platform, but nothing I really care to fix or work on, for the time being.

I should deprecate this module, as it served well for the last 4 years on the Web, but it's also completely useless in 2021.

Sorry to disappoint though, but I hope you understand where I come from, and where I am going.
